### PR TITLE
add support of token params (passport callback arity)

### PR DESCRIPTION
**Pull request by AlexeyKhristov**
add support of token params based on this if-block https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L190

### CODE REVIEW

**Comment by AlexeyKhristov** [comment]
up

**Comment by AlexeyKhristov** [comment]
@jonstorer could you please merge this pull request and publish new version on npm?

**Comment by jonstorer** [comment]
@AlexeyKhristov sorry! I'm just seeing this. My notifications must be off. I'll work on getting this in this week and getting it published.

**Comment by jonstorer** [comment]
@AlexeyKhristov we should probably add support for this entire block https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L180

**Comment by jonstorer** [comment]
@AlexeyKhristov https://github.com/shake-apps/passport-mocked/pull/9/files

**Pull request closed without merging**
